# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420955c2afa52b9d76ffee505e5fe87b1f15d765647bb69cef874240bfe5aac8d3e8aa7374a0dba52d69121d72f75e2300e607e0a423fb228c551ad16901fb1e

  facebook_api_key: <%= ENV["MEMAMUG_FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["MEMAMUG_FACEBOOK_API_SECRET"] %>

  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>

test:
  secret_key_base: 3b544c7e60923a879f6f1ed42068bb6e75dee285382739fb67bbe497ec0f1408bc68bef11678c293b7c7e32c83a6673d89ef57cd7bf15c166cc36f6ea23d72de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  facebook_api_key: <%= ENV["MEMAMUG_FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["MEMAMUG_FACEBOOK_API_SECRET"] %>

  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
